# Generated by Django 5.0.1 on 2024-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateField(verbose_name='datadevolucao'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='dataemprestimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='entregueEm',
            field=models.DateField(null=True, verbose_name='entregueem'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='idCliente',
            field=models.IntegerField(verbose_name='idcliente'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='idLivro',
            field=models.IntegerField(verbose_name='idlivro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='titulo'),
        ),
    ]
