# Generated by Django 5.0.1 on 2024-01-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_alter_emprestimo_datadevolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateField(verbose_name='dataDevolucao'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='dataEmprestimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='entregueEm',
            field=models.DateField(null=True, verbose_name='entregueEm'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='idCliente',
            field=models.IntegerField(verbose_name='idCliente'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='idLivro',
            field=models.IntegerField(verbose_name='idLivro'),
        ),
    ]
